name: ARCADIA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dcdbd9'
    - '#2c5818'
    - '#48657e'
    - '#789482'
    - '#fffefc'
  brandStrength: 0.15077827242203057
  lightness: 0.4811150326859206
  saturation: 0.44790905760601163
  rhythmicContrast: 0.8864588174037635
purpose: []
