name: ARCADIA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6215
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#225f80'
    - '#c0bdd0'
    - '#e0dfe7'
    - '#8b85a9'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
