name: ARCADIA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.0944
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf8ef'
    - '#bec7ea'
    - '#392e3f'
    - '#0a030a'
    - '#7078a3'
  brandStrength: 0.5
  lightness: 0.4811150326859206
  saturation: 0.1875
  rhythmicContrast: 0.8864588174037635
purpose: []
